# Generated by Django 4.1 on 2022-09-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=144)),
                ('lname', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('adress', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('state', models.TextField()),
                ('post_code', models.CharField(max_length=144)),
                ('date', models.DateField()),
            ],
        ),
    ]
