# Generated by Django 4.1 on 2022-09-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.TextField(max_length=222),
        ),
    ]
