# Generated by Django 4.1 on 2022-09-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_contact_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='post_code',
        ),
    ]
